---
title: "Validation_biomarkers"
output: html_notebook
---
Run Calculating_BA.Rmd for to1po2

Preparing variables
```{r}
colnames(amoris)[colnames(amoris) == "Kon"] <- "gender"
colnames(amoris)[colnames(amoris) == "Alder"] <- "age"
colnames(amoris)[colnames(amoris) == "Id"] <- "sampleID"

amoris <- amoris %>%
  mutate(status = ifelse(is.na(DODSDATn), 0, 1)) %>%
  mutate(time = as.numeric(difftime(lastDate, firstDate, units = "weeks")) / 4.33)

negative_counts <- sum(amoris$time < 0)
print(paste("Number of negative survival times:", negative_counts))

# Filtering out negative times
amoris <- amoris %>% filter(time >= 0)
```
Biomarkers
```{r}
# Biomarkers measures to be tested against mortality
BM <- c("S_Alb", "S_Krea", "TC", "TG", "S_K", "S_P", "Fe_maet", "S_Urea", "S_LD", "S_Ca", "fS_TIBC", "fS_Jaern", "S_Alp", "S_Urat", "S_FAMN", "S_Hapt", "fS_Gluk")

# Correct the initialization of HR_BA_adrd data frame
HR_BM <- data.frame(
  BA = rep(BM, each = 2),  # Repeat each BA measure twice
  outcome = rep("Mortality", times = length(BM) * 2),
  model = rep(c("Gender-adjusted model", "Multivariable model"), times = length(BM)),
  beta = NA, se = NA, HR = NA, lb = NA, ub = NA, p = NA, p_PH_BA = NA, global_p_PH_BA = NA,
  concordance = NA  # Add a column for the concordance index
)

for (j in 1:length(BM)) {
  # Gender-adjusted model
  fit_gender <- coxph(as.formula(paste("Surv(AgeAtFirstDate, AgeAtLastDate, status) ~", BM[j], "+ gender")), data = to1po2)
  coef_gender <- summary(fit_gender)
  row_index_gender <- (j * 2) - 1
  HR_BM[row_index_gender, c(4, 5, 9, 12)] <- c(coef_gender$coefficients[1, c(1, 3, 5)], coef_gender$concordance[1])
  HR_BM[row_index_gender, 6:8] <- coef_gender$conf.int[1, c(1, 3, 4)]
  HR_BM[row_index_gender, 10] <- cox.zph(fit_gender)$table[1, 3]
  HR_BM[row_index_gender, 11] <- cox.zph(fit_gender)$table[3, 3]
  
  # Multivariable model
  fit_multivariable <- coxph(as.formula(paste("Surv(AgeAtFirstDate, AgeAtLastDate, status) ~", BM[j], "+ gender + income_bins + NewUtbNiva")), data = to1po2)
  coef_multivariable <- summary(fit_multivariable)
  row_index_multivariable <- j * 2
  HR_BM[row_index_multivariable, c(4, 5, 9, 12)] <- c(coef_multivariable$coefficients[1, c(1, 3, 5)], coef_multivariable$concordance[1])
  HR_BM[row_index_multivariable, 6:8] <- coef_multivariable$conf.int[1, c(1, 3, 4)]
  HR_BM[row_index_multivariable, 10] <- cox.zph(fit_multivariable)$table[1, 3]
  HR_BM[row_index_multivariable, 11] <- cox.zph(fit_multivariable)$table[3, 3]
}

HR_BM_validation <- HR_BM

# Print the modified HR_BA_adrd data frame
print(HR_BM)
```
Again but different timescale
```{r}
# Biomarkers measures to be tested against mortality
BM <- c("S_Alb", "S_Krea", "TC", "TG", "S_K", "S_P", "Fe_maet", "S_Urea", "S_LD", "S_Ca", "fS_TIBC", "fS_Jaern", "S_Alp", "S_Urat", "S_FAMN", "S_Hapt", "fS_Gluk")

# Correct the initialization of HR_BA_adrd data frame
HR_BM <- data.frame(
  BA = rep(BM, each = 2),  # Repeat each BA measure twice
  outcome = rep("Mortality", times = length(BM) * 2),
  model = rep(c("Gender-adjusted model", "Multivariable model"), times = length(BM)),
  beta = NA, se = NA, HR = NA, lb = NA, ub = NA, p = NA, p_PH_BA = NA, global_p_PH_BA = NA,
  concordance = NA  # Add a column for the concordance index
)

for (j in 1:length(BM)) {
  # Gender-adjusted model
  fit_gender <- coxph(as.formula(paste("Surv(time, status) ~", BM[j], "+ gender")), data = to1po2)
  coef_gender <- summary(fit_gender)
  row_index_gender <- (j * 2) - 1
  HR_BM[row_index_gender, c(4, 5, 9, 12)] <- c(coef_gender$coefficients[1, c(1, 3, 5)], coef_gender$concordance[1])
  HR_BM[row_index_gender, 6:8] <- coef_gender$conf.int[1, c(1, 3, 4)]
  HR_BM[row_index_gender, 10] <- cox.zph(fit_gender)$table[1, 3]
  HR_BM[row_index_gender, 11] <- cox.zph(fit_gender)$table[3, 3]
  
  # Multivariable model
  fit_multivariable <- coxph(as.formula(paste("Surv(time, status) ~", BM[j], "+ gender + income_bins + NewUtbNiva")), data = to1po2)
  coef_multivariable <- summary(fit_multivariable)
  row_index_multivariable <- j * 2
  HR_BM[row_index_multivariable, c(4, 5, 9, 12)] <- c(coef_multivariable$coefficients[1, c(1, 3, 5)], coef_multivariable$concordance[1])
  HR_BM[row_index_multivariable, 6:8] <- coef_multivariable$conf.int[1, c(1, 3, 4)]
  HR_BM[row_index_multivariable, 10] <- cox.zph(fit_multivariable)$table[1, 3]
  HR_BM[row_index_multivariable, 11] <- cox.zph(fit_multivariable)$table[3, 3]
}

#HR_BM <- HR_BM

# Print the modified HR_BA_adrd data frame
print(HR_BM)
```

## Per sex
```{r}
BM <- c("S_Alb", "S_Krea", "TC", "TG", "S_K", "S_P", "Fe_maet", "S_Urea", "S_LD", "S_Ca", "fS_TIBC", "fS_Jaern", "S_Alp", "S_Urat", "S_FAMN", "S_Hapt", "fS_Gluk")

# Initialize HR_BA data frame
HR_BM_g <- data.frame(
  BA = rep(BM, each = 2),
  Gender = rep(c("Men", "Women"), times = length(BM)),
  model = rep("BA measurm. per gender", times = 2 * length(BM)),
  beta = NA, se = NA, HR = NA,
  CI_lower = NA, CI_upper = NA, P_PH_BA = NA, global_p_PH_BA = NA, concordance = NA, N = NA
)

for (j in 1:length(BM)) {
  for (gender_group in c("Men", "Women")) {
    # Subset data based on new_gender
    data_subset <- to1po2[to1po2$new_gender == gender_group, ]

    # Fit Cox model for the BA measure (without 'new_gender' as a covariate)
    fit_gender <- coxph(as.formula(paste("Surv(AgeAtFirstDate, AgeAtLastDate, status) ~", BM[j])), data = data_subset)
    coef_gender <- summary(fit_gender)

    # Determine row index for updating HR_BA
    row_index <- if (gender_group == "Men") (j - 1) * 2 + 1 else j * 2

    # Update HR_BA with model results
    HR_BM_g[row_index, c("beta", "se", "HR")] <- coef_gender$coefficients[1, c(1, 3, 2)]
    HR_BM_g[row_index, c("CI_lower", "CI_upper")] <- coef_gender$conf.int[1, c(3, 4)]
    HR_BM_g[row_index, "P_PH_BA"] <- cox.zph(fit_gender)$table[1, 3]
    HR_BM_g[row_index, "global_p_PH_BA"] <- cox.zph(fit_gender)$table[2, 3]
    HR_BM_g[row_index, "concordance"] <- coef_gender$concordance[1]
    HR_BM_g[row_index, "N"] <- coef_gender$n
  }
}

#HR_BM_g <- HR_BM_g

# Print the updated HR_BA data frame
print(HR_BM_g)
```
## Per age group 
```{r}
BM <- c("S_Alb", "S_Krea", "TC", "TG", "S_K", "S_P", "Fe_maet", "S_Urea", "S_LD", "S_Ca", "fS_TIBC", "fS_Jaern", "S_Alp", "S_Urat", "S_FAMN", "S_Hapt", "fS_Gluk")

# Initialize HR_BA data frame
HR_BM_ag <- data.frame(
  BA = rep(BM, each = 2),
  AgeGroup = rep(c("Under 65", "65 and over"), times = length(BM)),
  model = rep("BA measurm. per agegroup", times = 2 * length(BM)),
  beta = NA, se = NA, HR = NA,
  CI_lower = NA, CI_upper = NA, P_PH_BA = NA, global_p_PH_BA = NA, concordance = NA, N = NA
)

for (j in 1:length(BM)) {
  # Loop over each BA measure
  for (age_group in c("Under 65", "65 and over")) {
    # Subset data based on age group
    if (age_group == "Under 65") {
      data_subset <- to1po2[to1po2$age < 65, ]
    } else {
      data_subset <- to1po2[to1po2$age >= 65, ]
    }

    # Fit gender-adjusted model
    fit_gender <- coxph(as.formula(paste("Surv(AgeAtFirstDate, AgeAtLastDate, status) ~", BM[j], "+ gender")), data = data_subset)
    coef_gender <- summary(fit_gender)

    # Determine row index for updating HR_BA
    if (age_group == "Under 65") {
      row_index <- (j - 1) * 2 + 1
    } else {
      row_index <- j * 2
    }
    
    # Update HR_BA with model results
    HR_BM_ag[row_index, c("beta", "se", "HR")] <- coef_gender$coefficients[1, c(1, 3, 2)]
    HR_BM_ag[row_index, c("CI_lower", "CI_upper")] <- coef_gender$conf.int[1, c(3, 4)]
    HR_BM_ag[row_index, "P_PH_BA"] <- cox.zph(fit_gender)$table[1, 3]
    HR_BM_ag[row_index, "global_p_PH_BA"] <- cox.zph(fit_gender)$table[3, 3]
    HR_BM_ag[row_index, "concordance"] <- coef_gender$concordance[1]
    HR_BM_ag[row_index, "N"] <- coef_gender$n
  }
}

#HR_BM_ag <- HR_BM_ag

# Print the updated HR_BA data frame
print(HR_BM_ag)
```

#============================================

#============================================


BA mortality validation
```{r}
# Biomarkers measures to be tested against mortality
BioAge_BA <- c("kdm", "kdm_advance", "kdm_res", "phenoage", "phenoage_advance","phenoage_res", "hd", "hd_res","hd_log", "hd_log_res", "age", "AgeAtFirstDate")

# Correct the initialization of HR_BA_adrd data frame
HR_BA_measurement <- data.frame(
  BA = rep(BioAge_BA, each = 2),  # Repeat each BA measure twice
  outcome = rep("Mortality", times = length(BioAge_BA) * 2),
  model = rep(c("Gender-adjusted model", "Multivariable model"), times = length(BioAge_BA)),
  beta = NA, se = NA, HR = NA, lb = NA, ub = NA, p = NA, p_PH_BA = NA, global_p_PH_BA = NA,
  concordance = NA  # Add a column for the concordance index
)

for (j in 1:length(BioAge_BA)) {
  # Gender-adjusted model
  fit_gender <- coxph(as.formula(paste("Surv(AgeAtFirstDate, AgeAtLastDate, status) ~", BioAge_BA[j], "+ gender")), data = to1po2)
  coef_gender <- summary(fit_gender)
  row_index_gender <- (j * 2) - 1
  HR_BA_measurement[row_index_gender, c(4, 5, 9, 12)] <- c(coef_gender$coefficients[1, c(1, 3, 5)], coef_gender$concordance[1])
  HR_BA_measurement[row_index_gender, 6:8] <- coef_gender$conf.int[1, c(1, 3, 4)]
  HR_BA_measurement[row_index_gender, 10] <- cox.zph(fit_gender)$table[1, 3]
  HR_BA_measurement[row_index_gender, 11] <- cox.zph(fit_gender)$table[3, 3]
  
  # Multivariable model
  fit_multivariable <- coxph(as.formula(paste("Surv(AgeAtFirstDate, AgeAtLastDate, status) ~", BioAge_BA[j], "+ gender + income_bins + NewUtbNiva")), data = to1po2)
  coef_multivariable <- summary(fit_multivariable)
  row_index_multivariable <- j * 2
  HR_BA_measurement[row_index_multivariable, c(4, 5, 9, 12)] <- c(coef_multivariable$coefficients[1, c(1, 3, 5)], coef_multivariable$concordance[1])
  HR_BA_measurement[row_index_multivariable, 6:8] <- coef_multivariable$conf.int[1, c(1, 3, 4)]
  HR_BA_measurement[row_index_multivariable, 10] <- cox.zph(fit_multivariable)$table[1, 3]
  HR_BA_measurement[row_index_multivariable, 11] <- cox.zph(fit_multivariable)$table[3, 3]
}

HR_BA_measurement <- HR_BA_measurement

# Print the modified HR_BA_adrd data frame
print(HR_BA_measurement)
```
##Per gender
```{r}
BioAge_BA <- c("kdm", "kdm_advance", "kdm_res", "phenoage", "phenoage_advance","phenoage_res", "hd", "hd_res","hd_log", "hd_log_res", "age", "AgeAtFirstDate")

# Initialize HR_BA data frame
HR_BA_measurement_g <- data.frame(
  BA = rep(BA_measures, each = 2),
  Gender = rep(c("Men", "Women"), times = length(BA_measures)),
  model = rep("BA measurm. per gender", times = 2 * length(BA_measures)),
  beta = NA, se = NA, HR = NA,
  CI_lower = NA, CI_upper = NA, P_PH_BA = NA, global_p_PH_BA = NA, concordance = NA, N = NA
)

for (j in 1:length(BA_measures)) {
  for (gender_group in c("Men", "Women")) {
    # Subset data based on new_gender
    data_subset <- to1po2[to1po2$new_gender == gender_group, ]

    # Fit Cox model for the BA measure (without 'new_gender' as a covariate)
    fit_gender <- coxph(as.formula(paste("Surv(AgeAtFirstDate, AgeAtLastDate, status) ~", BioAge_BA[j])), data = data_subset)
    coef_gender <- summary(fit_gender)

    # Determine row index for updating HR_BA
    row_index <- if (gender_group == "Men") (j - 1) * 2 + 1 else j * 2

    # Update HR_BA with model results
    HR_BA_measurement_g[row_index, c("beta", "se", "HR")] <- coef_gender$coefficients[1, c(1, 3, 2)]
    HR_BA_measurement_g[row_index, c("CI_lower", "CI_upper")] <- coef_gender$conf.int[1, c(3, 4)]
    HR_BA_measurement_g[row_index, "P_PH_BA"] <- cox.zph(fit_gender)$table[1, 3]
    HR_BA_measurement_g[row_index, "global_p_PH_BA"] <- cox.zph(fit_gender)$table[2, 3]
    HR_BA_measurement_g[row_index, "concordance"] <- coef_gender$concordance[1]
    HR_BA_measurement_g[row_index, "N"] <- coef_gender$n
  }
}

#HR_BA_measurement_g <- HR_BA_measurement_g

# Print the updated HR_BA data frame
print(HR_BA_measurement_g)
```
## Per age group
```{r}
BioAge_BA <- c("kdm", "kdm_advance", "kdm_res", "phenoage", "phenoage_advance","phenoage_res", "hd", "hd_res","hd_log", "hd_log_res", "age", "AgeAtFirstDate")

# Initialize HR_BA data frame
HR_BA_ag <- data.frame(
  BA = rep(BioAge_BA, each = 2),
  AgeGroup = rep(c("Under 65", "65 and over"), times = length(BioAge_BA)),
  model = rep("BA measurm. per agegroup_agegroup", times = 2 * length(BioAge_BA)),
  beta = NA, se = NA, HR = NA,
  CI_lower = NA, CI_upper = NA, P_PH_BA = NA, global_p_PH_BA = NA, concordance = NA, N = NA
)

for (j in 1:length(BioAge_BA)) {
  # Loop over each BA measure
  for (age_group in c("Under 65", "65 and over")) {
    # Subset data based on age group
    if (age_group == "Under 65") {
      data_subset <- to1po2[to1po2$age < 65, ]
    } else {
      data_subset <- to1po2[to1po2$age >= 65, ]
    }

    # Fit gender-adjusted model
    fit_gender <- coxph(as.formula(paste("Surv(AgeAtFirstDate, AgeAtLastDate, status) ~", BioAge_BA[j], "+ gender")), data = data_subset)
    coef_gender <- summary(fit_gender)

    # Determine row index for updating HR_BA
    if (age_group == "Under 65") {
      row_index <- (j - 1) * 2 + 1
    } else {
      row_index <- j * 2
    }
    
    # Update HR_BA with model results
    HR_BA_ag[row_index, c("beta", "se", "HR")] <- coef_gender$coefficients[1, c(1, 3, 2)]
    HR_BA_ag[row_index, c("CI_lower", "CI_upper")] <- coef_gender$conf.int[1, c(3, 4)]
    HR_BA_ag[row_index, "P_PH_BA"] <- cox.zph(fit_gender)$table[1, 3]
    HR_BA_ag[row_index, "global_p_PH_BA"] <- cox.zph(fit_gender)$table[3, 3]
    HR_BA_ag[row_index, "concordance"] <- coef_gender$concordance[1]
    HR_BA_ag[row_index, "N"] <- coef_gender$n
  }
}

#HR_BM_ag <- HR_BM_ag

# Print the updated HR_BA data frame
print(HR_BA_ag)
```